config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :locals
  resources :bussines_to_bussinesses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bussines_to_bussiness.rb
class BussinesToBussiness < ApplicationRecord
end

app/models/local.rb
class Local < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bussines_to_bussinesses_controller.rb
class BussinesToBussinessesController < ApplicationController
  before_action :set_bussines_to_bussiness, only: [:show, :edit, :update, :destroy]

  # GET /bussines_to_bussinesses
  # GET /bussines_to_bussinesses.json
  def index
    @bussines_to_bussinesses = BussinesToBussiness.all
  end

  # GET /bussines_to_bussinesses/1
  # GET /bussines_to_bussinesses/1.json
  def show
  end

  # GET /bussines_to_bussinesses/new
  def new
    @bussines_to_bussiness = BussinesToBussiness.new
  end

  # GET /bussines_to_bussinesses/1/edit
  def edit
  end

  # POST /bussines_to_bussinesses
  # POST /bussines_to_bussinesses.json
  def create
    @bussines_to_bussiness = BussinesToBussiness.new(bussines_to_bussiness_params)

    respond_to do |format|
      if @bussines_to_bussiness.save
        format.html { redirect_to @bussines_to_bussiness, notice: 'Bussines to bussiness was successfully created.' }
        format.json { render :show, status: :created, location: @bussines_to_bussiness }
      else
        format.html { render :new }
        format.json { render json: @bussines_to_bussiness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bussines_to_bussinesses/1
  # PATCH/PUT /bussines_to_bussinesses/1.json
  def update
    respond_to do |format|
      if @bussines_to_bussiness.update(bussines_to_bussiness_params)
        format.html { redirect_to @bussines_to_bussiness, notice: 'Bussines to bussiness was successfully updated.' }
        format.json { render :show, status: :ok, location: @bussines_to_bussiness }
      else
        format.html { render :edit }
        format.json { render json: @bussines_to_bussiness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bussines_to_bussinesses/1
  # DELETE /bussines_to_bussinesses/1.json
  def destroy
    @bussines_to_bussiness.destroy
    respond_to do |format|
      format.html { redirect_to bussines_to_bussinesses_url, notice: 'Bussines to bussiness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bussines_to_bussiness
      @bussines_to_bussiness = BussinesToBussiness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bussines_to_bussiness_params
      params.require(:bussines_to_bussiness).permit(:sales_by_period_cash, :sales_by_period_units, :inventory_cash, :inventory_units)
    end
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all
  end

  # GET /locals/1
  # GET /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:name, :code)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bussines_to_bussinesses_helper.rb
module BussinesToBussinessesHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bussines_to_bussinesses/_form.html.erb
<%= form_with(model: bussines_to_bussiness, local: true) do |form| %>
  <% if bussines_to_bussiness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bussines_to_bussiness.errors.count, "error") %> prohibited this bussines_to_bussiness from being saved:</h2>

      <ul>
        <% bussines_to_bussiness.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sales_by_period_cash %>
    <%= form.number_field :sales_by_period_cash %>
  </div>

  <div class="field">
    <%= form.label :sales_by_period_units %>
    <%= form.number_field :sales_by_period_units %>
  </div>

  <div class="field">
    <%= form.label :inventory_cash %>
    <%= form.number_field :inventory_cash %>
  </div>

  <div class="field">
    <%= form.label :inventory_units %>
    <%= form.number_field :inventory_units %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bussines_to_bussinesses/edit.html.erb
<h1>Editing Bussines To Bussiness</h1>

<%= render 'form', bussines_to_bussiness: @bussines_to_bussiness %>

<%= link_to 'Show', @bussines_to_bussiness %> |
<%= link_to 'Back', bussines_to_bussinesses_path %>

app/views/bussines_to_bussinesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bussines To Bussinesses</h1>

<table>
  <thead>
    <tr>
      <th>Sales by period cash</th>
      <th>Sales by period units</th>
      <th>Inventory cash</th>
      <th>Inventory units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bussines_to_bussinesses.each do |bussines_to_bussiness| %>
      <tr>
        <td><%= bussines_to_bussiness.sales_by_period_cash %></td>
        <td><%= bussines_to_bussiness.sales_by_period_units %></td>
        <td><%= bussines_to_bussiness.inventory_cash %></td>
        <td><%= bussines_to_bussiness.inventory_units %></td>
        <td><%= link_to 'Show', bussines_to_bussiness %></td>
        <td><%= link_to 'Edit', edit_bussines_to_bussiness_path(bussines_to_bussiness) %></td>
        <td><%= link_to 'Destroy', bussines_to_bussiness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bussines To Bussiness', new_bussines_to_bussiness_path %>

app/views/bussines_to_bussinesses/new.html.erb
<h1>New Bussines To Bussiness</h1>

<%= render 'form', bussines_to_bussiness: @bussines_to_bussiness %>

<%= link_to 'Back', bussines_to_bussinesses_path %>

app/views/bussines_to_bussinesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sales by period cash:</strong>
  <%= @bussines_to_bussiness.sales_by_period_cash %>
</p>

<p>
  <strong>Sales by period units:</strong>
  <%= @bussines_to_bussiness.sales_by_period_units %>
</p>

<p>
  <strong>Inventory cash:</strong>
  <%= @bussines_to_bussiness.inventory_cash %>
</p>

<p>
  <strong>Inventory units:</strong>
  <%= @bussines_to_bussiness.inventory_units %>
</p>

<%= link_to 'Edit', edit_bussines_to_bussiness_path(@bussines_to_bussiness) %> |
<%= link_to 'Back', bussines_to_bussinesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locals/_form.html.erb
<%= form_with(model: local, local: true) do |form| %>
  <% if local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
        <% local.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locals/edit.html.erb
<h1>Editing Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

app/views/locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locals.each do |local| %>
      <tr>
        <td><%= local.name %></td>
        <td><%= local.code %></td>
        <td><%= link_to 'Show', local %></td>
        <td><%= link_to 'Edit', edit_local_path(local) %></td>
        <td><%= link_to 'Destroy', local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Local', new_local_path %>

app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form', local: @local %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @local.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @local.code %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>